### ISSUE TITLE
Truncate http(s):// from pasted URL in the textbox

### ISSUE THREAD

**Issue by LuciousLisa** [swiperproxy/swiperproxy#13]
Step 1: Copy URL that you want to visit using the Swiperproxy
Step 2: Click bookmark for Swiperproxy
Step 3: Ctrl+V
Step 4: Enter
Step 5: ????
Step 6: Profit

A simple copy/paste would improve user experience, so this would be a valuable enhancement.

**Comment by Techwolf12** [comment]
As we can't use javascript we must do this server sided.   
Thanks for your input!

**Comment by abrioso** [comment]
Hi,

In ULisboa's swiperproxy implementation we use a different approach, as we use Apache to serve the proxy frontpage and the endpoints "/http://" and "/https://" to distinguish between non-ssl and ssl ProxyPass to be sent to swiperproxy.

As such, the input field in our frontpage accepts URLs started with http:// and https:// and the request is sent to the corresponding swiperproxy (http or https).

The main problem in this approach is that you need a webserver with reverse proxy support as a dependency.

**Comment by Argure** [comment]
@Techwolf12 Since I'm in exam period I'm volunteering you to write the docs on this.

**Comment by Techwolf12** [comment]
@Argure Thanks <3 ;)

**Comment by Argure** [comment]
Fixed and will be rolled out in 1.1 release.
