### ISSUE TITLE
cookies required

### ISSUE THREAD

**Issue by qkhhly** [swiperproxy/swiperproxy#15]
Hi! I have successfully install swiperproxy and it works like charm! However, when I try to login into my facebook or my gmail account I got an error says 

    Cookies Required. Cookies are not enabled on your browser. 
    Please enable cookies in your browser preferences to continue.

Of course cookies are enabled in my browser and I can login to those accounts when not using swiperproxy. I didn't find a conf option to enable or disable cookies. Did I miss anything? How shall I enable cookies in swiperproxy? Thanks!

**Comment by Argure** [comment]
Facebook works fine on my machine(tm)

![Image](https://i.imgur.com/ceMVfLD.png)

Gmail doesn't, because of some server-side Gmail-fu that I can't get a handle on real quick. I'll take a deeper look into what Gmail exactly does and if we can fix this in the proxy.

**Comment by jianlingzh** [comment]
Do you why the "cookies not enabled" error appear? Is there any conf options I need to tweak? I appreciate if you could point me to the right direction.

**Comment by Argure** [comment]
Gmail has resolved this issue on remote host.
