### ISSUE TITLE
SysV Init script logic errors

### ISSUE THREAD

**Issue by Diftraku** [swiperproxy/swiperproxy#16]
When running the proxy as a daemon, you can override the directory it is by changing the defaults.

Only problem is, the defaults are loaded AFTER the check for the `Proxy.py`. See the diff below:
```
diff include/init/sysvinit.sh /etc/init.d/swiperproxy 
16d15
< 
25,27d23
< # Exit if the package is not installed
< [ -x "$DAEMON" ] || exit 0
< 
30a27,29
> # Exit if the package is not installed
> [ -x "$DAEMON" ] || exit 0
> 
37a37
> 	echo "Starting"
```

So the lines look like this
```
# Read default configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0
```

Also, the start of the file where the hashbang is located has an extra space, not sure if it makes any difference.

**Comment by Argure** [comment]
Resolved in a606d6f77e60587d134bf78c96f103a745b25918
