### ISSUE TITLE
Proxy server always return Access Denied 403

### ISSUE THREAD

**Issue by zihaol1** [swiperproxy/swiperproxy#17]
![screen](https://cloud.githubusercontent.com/assets/14949203/10266473/9a1163cc-6a32-11e5-9566-5332aedf16bd.png)
I set up the firefox using foxyproxy and my proxy server running on localhost listening on port 8001 for http. The port for rewrite URL is 80. But whenever I tried to request some http webpage, it returns Access Denied 403 error. Although it does seems that requests went through to the remote server. any idea why?

**Comment by zihaol1** [comment]
never mind, hacked it out.

**Comment by Argure** [comment]
Glad to see you figured it out. :)

**Comment by tvkkpt** [comment]
Hi @zihaol1 . I'm encountering the same issue. Would you mind telling me how you've solved it please?

**Comment by zihaol1** [comment]
@tvkkpt I believe the issue is that the swiperproxy by default does not allow localhost access. So I just changed the code to allow for that and then rerun the proxy.

**Comment by tvkkpt** [comment]
Thanks @zihaol1. I also figured it out. In my case, I need to set http_endpoint=/ and https_endpoints=/ so the urls can be properly transformed.
