### ISSUE TITLE
ImportError: No module named streamhtmlparser

### ISSUE THREAD

**Issue by DrnSln** [swiperproxy/swiperproxy#7]
```
# python -V
Python 2.7.3

# python Proxy.py
Traceback (most recent call last):
  File "./Proxy.py", line 38, in <module>
    from Page import Page
  File "/mnt/work/python/swiperproxy/Page.py", line 23, in <module>
    from streamhtmlparser import *
ImportError: No module named streamhtmlparser
```

No details about installing streamhtmlparser in either [Quickstart](https://swiperproxy.github.io/quickstart.html) or [Sysadmin](https://swiperproxy.github.io/documentation/sysadmin.html) pages.

**Comment by Argure** [comment]
Quickstart lists streamhtmlparser as a dependency:
>streamhtmlparser, 0.1 or higher

It also has the instructions for compiling:

>Compile streamhtmlparser and its Python module:
>$ cd /opt/SwiperProxy/swiperproxy/include/streamhtmlparser
>$ ./configure
>$ make
>$ make install
>$ cd src/py-streamhtmlparser
>$ make
>$ make install
